## Q1
What is the output?

In [2]:
import numpy as np

In [4]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])
x[(x >= -5) & (x <= 15)]                                   # numbers in range between -5 and 15

array([-5,  9, -3,  5, 10])

### Q2   sort np array

In [8]:
a = np.array(['Ram', 'Astha', 'Raghavendra'])
np.sort(a), a     # This is not inplace sort

a.sort(), a   # inplace sort


(None, array(['Astha', 'Raghavendra', 'Ram'], dtype='<U11'))

In [10]:
# Comparing two np arrays
a1 = np.array(['Ram','Astha','Brahat'])
a2 = np.array(['Shyam','Kalyan','Naveen'])

a1 > a2

array([False, False, False])

### Q3 Concatenate

In [14]:
a = np.array([[1,2,3], [4, 5, 6]])      #  2 * 3
b = np.array([[9], [10]])               # 2 * 1

np.concatenate((a, b), axis=1)       # Added new matrix as column 

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [20]:
a = np.array([[1,2,3], [4, 5, 6]])      # 2 * 3
b = np.array([[7, 8, 9]])               #  1 * 3

np.concatenate((a, b), axis=0)         # Added new matrix as row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Q4 Create 2D array using reshape

In [22]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Q5  numpy Addition   -  broadcasting

In [26]:
a = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
a + 1,   np.array(list(map(lambda x: x + 1, a))),  np.array([i + 1 for i in a])

(array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6]),
 array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6]),
 array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6]))

### Q6  Manipulate np array

In [35]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Q7 argsort

Given a matrix, sort based on particular column corresponding rows should get moved.


5 3 9                         
2 1 4   
7 6 8

sort on second column
Output

[[2 1 4]    
 [5 3 9]    
 [7 6 8]]   
 
 

In [37]:
a = np.array([[5, 3, 9], [2, 1, 4], [7, 6, 8]])
a

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [41]:
a[:, 1].argsort()    # gives positions

array([1, 0, 2], dtype=int64)

In [43]:
# After getting positions in the same order place rows
a[a[:, 1].argsort()]

array([[2, 1, 4],
       [5, 3, 9],
       [7, 6, 8]])

In [48]:
a[1, :].argsort()

array([1, 0, 2], dtype=int64)

In [49]:
a[[1, 0, 2]]

array([[2, 1, 4],
       [5, 3, 9],
       [7, 6, 8]])

In [50]:
a

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [51]:
b = a.T

In [52]:
b

array([[5, 2, 7],
       [3, 1, 6],
       [9, 4, 8]])

In [54]:
b[[1, 0, 2]].T

array([[3, 5, 9],
       [1, 2, 4],
       [6, 7, 8]])

### Q8
5 10 3

Start of the sequence = 5, length of the sequence = 10 and step = 3.

First point would be the start point only, second point = start + 1*step = 5 + 1*3 =8, ....... 10th point = start + (10-1)*step = 5 + 9*3 = 32


In [55]:
start = 5 
step = 3
nums = 10

l = []
for i in range(10):
    l.append(start + (step * i))
np.array(l)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### Q9 

[[ 7 4 8 5 1]   
 [ 8 0 11 3 5]   
 [ 9 6 3 5 0]   
 [ 1 5 7 3 2]   
 [ 4 7 2 9 1]]   
 
 pick all elements that are even and create a square array using re shape

In [56]:
a = np.array([[7, 4, 8, 5, 1], [8, 0, 11, 3, 5], [9, 6, 3, 5, 0], [1, 5, 7, 3, 2], [4, 7, 2, 9, 1]])
a

array([[ 7,  4,  8,  5,  1],
       [ 8,  0, 11,  3,  5],
       [ 9,  6,  3,  5,  0],
       [ 1,  5,  7,  3,  2],
       [ 4,  7,  2,  9,  1]])

In [58]:
b = a[a % 2 == 0]
b

array([4, 8, 8, 0, 6, 0, 2, 4, 2])

In [61]:
siz = int(len(b) ** 0.5)
b.reshape((siz, siz))

array([[4, 8, 8],
       [0, 6, 0],
       [2, 4, 2]])

### Q10   MSE

In [63]:
a = np.array([1, 1, 2, 2, 4])
b = np.array([0.6, 1.29, 1.99, 2.69, 3.4])

In [67]:
np.round(np.sum((a - b) ** 2) / len(a), 2)

0.22

### Q11  sigmoid

In [68]:
a = np.array([-2, -1, 0, 1, 2])

In [69]:
a

array([-2, -1,  0,  1,  2])

In [74]:
b = 1 / (1 + np.exp(-a))

In [75]:
np.round(b, 2)

array([0.12, 0.27, 0.5 , 0.73, 0.88])

### Q12  Rotate the image /matrix clock wise by 90

Input:

[[1 2 3]   
 [4 5 6]  
 [7 8 9]]  
 
 Output:
 
 [[7 4 1]  
 [8 5 2]   
 [9 6 3]]  


In [77]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [80]:
np.rot90(a, -1)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [85]:
# Another way

# Actuall array shape : m * n
# new Array size will be : n * m

a = np.array([[1], [2]])
m, n = a.shape
b = np.arange(m * n).reshape((n, m))

b.shape


for i in range(n):
    b[i] = a[:, i][::-1]

b



    

array([[2, 1]])