In [1]:
import numpy as np

In [2]:
l = range(1000000)

In [3]:
%timeit [i ** 2 for i in l]

218 ms ± 7.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
n = np.arange(1000000)

In [5]:
%timeit n**2

1.29 ms ± 71.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
arr1 = np.array([1, 2, 3])

In [7]:
arr1

array([1, 2, 3])

In [8]:
arr1.ndim

1

In [9]:
arr1.shape

(3,)

In [11]:
np.arange(1, 5, 1.5)

array([1. , 2.5, 4. ])

In [15]:
np.linspace(1,10, 13, endpoint=False)

array([1.        , 1.69230769, 2.38461538, 3.07692308, 3.76923077,
       4.46153846, 5.15384615, 5.84615385, 6.53846154, 7.23076923,
       7.92307692, 8.61538462, 9.30769231])

In [16]:
np.square(np.arange(1, 10))

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
np.linspace(1,1, 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
a = [1, 2, 3]

In [22]:
a

[1, 2, 3]

In [23]:
dir(a)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [25]:
a = np.array([1, 2, 'hi'])

In [26]:
a.dtype

dtype('<U11')

In [27]:
a

array(['1', '2', 'hi'], dtype='<U11')

In [28]:
np.array([0, 10, 100], dtype='int64') ** 100

array([0, 0, 0], dtype=int64)

In [33]:
np.array([0, 10, 100], dtype='long') ** 10

array([         0, 1410065408, 1661992960], dtype=int32)

In [35]:
a=np.arange(1, 13)

In [36]:
a.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [37]:
a.reshape(-1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [41]:
a.reshape(4, -2)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
a = np.arange(12).reshape(3, 4)

In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[:, 1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [46]:
a[:, [1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [47]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a[a>10]

array([11])

In [49]:
a > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [50]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [51]:
a = [1,2,3,4,5]

In [52]:
a

[1, 2, 3, 4, 5]

In [53]:
b = a[3:]

In [54]:
b

[4, 5]

In [55]:
id(a)

2226384022144

In [56]:
id(b)

2226387614016

In [57]:
b = np.arange(12).reshape(3,4
                         )

In [58]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a


[1, 2, 3, 4, 5]

In [61]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b[b%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [63]:
b[(b%2==0) & (b%5==0)]

array([ 0, 10])